# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IsasG03PYi6yGqcxPJRbE2m62tReU5Wg
"""

import pandas as pd

df = pd.read_csv('/customer_booking.csv', encoding='latin1')

df.head()

df.info()

## Check First Few Rows
df.head(10)

## Check Missing Values
df.isnull().sum()

## checking target coloum
df['booking_complete'].value_counts()

## Convert text columns
df = pd.get_dummies(df, drop_first=True)

## creating a features and target
X = df.drop('booking_complete', axis=1)

y = df['booking_complete']

## split train/ testing the data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

## trainning random forest model
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

## make prediction
prediction = model.predict(X_test)

## checkng the Accuracy
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, prediction)

print("Accuracy:", accuracy)

## report
from sklearn.metrics import classification_report

print(classification_report(y_test, prediction))

importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
})

importance = importance.sort_values(
    by='Importance',
    ascending=False
)

importance.head(10)

## Bar chart
import matplotlib.pyplot as plt

importance.head(10).plot(
    x='Feature',
    y='Importance',
    kind='bar'
)

plt.title("Top 10 Important Features")

plt.show()